### ISSUE TITLE
`register_rb_step_definition': undefined method `register_rb_step_definition' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by knightinfire** [cucumber/cucumber-ruby-core#153]
I am having such an error while trying to use the following script 

require 'watir'
require 'webdrivers'
require 'cucumber'

Given /^I have entered "([^"]*)" into the query$/ do |term|
@browser ||= Watir::Browser.new :firefox
@browser.goto "google.com"
@browser.text_field(:name => "q").set term
end

When /^I click "([^"]*)"$/ do |button_name|
@browser.button.click
end

Then /^I should see some results$/ do
@browser.div(:id => "resultStats").wait_until_present
@browser.div(:id => "resultStats").should exist
@browser.close
end

And the error again

/usr/local/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/dsl.rb:30:in `register_rb_step_definition': undefined method `register_rb_step_definition' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/cucumber-3.1.0/lib/cucumber/glue/dsl.rb:132:in `register_rb_step_definition'
        from Cucumberruby.rb:6:in `<main>'

I have tried to use different regex or  empty ones, still having the error. Please Help..

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:cucumber-3.1.0
* Operating System and version: Mac OSX
* Link to your project:

**Comment by danascheider** [comment]
Hi there @knightinfire! I'm taking a look at this on my machine and will let you know what I find out.

**Comment by danascheider** [comment]
Hi @knightinfire! So I made this [gist](https://gist.github.com/danascheider/6f57d9722bf89f9d2f1afd7fd6bdfcaf) demonstrating how I set this up to run. I used a clean RVM gemset with Ruby 2.4.0 and ran `gem install bundler && bundle install` to install all the gems. Then, I used `cucumber --init` to create the `features` directory and subdirectories.

I did not get the same error you did. I got a step failure on the second step with the following:
```
Feature: Figure out issue 153

  Scenario: Search for something              # features/test.feature:3
    Given I have entered "foo" into the query # features/step_definitions/test_steps.rb:1
    When I click "Google Search"              # features/step_definitions/test_steps.rb:7
      element located, but timed out after 30 seconds, waiting for #<Watir::Button: located: true; {:tag_name=>"button"}> to be present (Watir::Exception::UnknownObjectException)
      ./features/step_definitions/test_steps.rb:8:in `/^I click "([^"]*)"$/'
      features/test.feature:5:in `When I click "Google Search"'
    Then I should see some results            # features/step_definitions/test_steps.rb:11

Failing Scenarios:
cucumber features/test.feature:3 # Scenario: Search for something

1 scenario (1 failed)
3 steps (1 failed, 1 skipped, 1 passed)
0m36.267s
```
I fixed this failure by changing the code in the step definition to:
```
@browser.button(:text => button_name).click
```
Next, the final step failed because my Gemfile did not include `gem "rspec", "~> 3.7.0"`. Once I added that, the scenario passed.

I'm wondering if another gem you're using is modifying the behavior of Cucumber such that this error occurs. I would be able to get to the bottom of this more quickly if you were able to provide your Gemfile and Gemfile.lock. My other questions would be:
* At what point in execution does this error occur? Does the suite run at all?
* What Ruby version manager are you using/how are you managing your gemsets?

Please let me know any other information you have. So sorry it's taken us a while to get to your question!

**Comment by luke-hill** [comment]
Just for clarity also (Because there is an outstanding issue), are you using RubyMine, if so what version.?

RubyMine has known compatibility issues with All versions of Cucumber3. And fixes are still ongoing.

If you're not using RubyMine, ignore my question.

**Comment by danascheider** [comment]
@luke-hill Good to know!

**Comment by knightinfire** [comment]
@danascheider 
My problem has not been solved, I have reinstalled cucumber, tried to install gem file of rspec, and added rspec to my script with include, nothing worked, still getting the same error.
I am getting the error after calling my script with ruby myscript.rb
Should I call the feature file only? i thought it would work directly from the ruby file ?

My ruby version : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

I do not use a specific gem manager, default one from terminal.
Also I think the error originates from the regex that I am using, Do you think there is something wrong with it ?
